
export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const GET_USERS_BEGIN = 'GET_USERS_BEGIN'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'

export const DELETE_USER_BEGIN = 'DELETE_USER_BEGIN'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_LAB_BEGIN = 'CREATE_LAB_BEGIN'
export const CREATE_LAB_SUCCESS = 'CREATE_LAB_SUCCESS'
export const CREATE_LAB_ERROR = 'CREATE_LAB_ERROR'

export const GET_LABS_BEGIN = 'GET_LABS_BEGIN'
export const GET_LABS_SUCCESS = 'GET_LABS_SUCCESS'

export const SET_EDIT_LAB = 'SET_EDIT_LAB'

export const EDIT_LAB_BEGIN = 'EDIT_LAB_BEGIN'
export const EDIT_LAB_SUCCESS = 'EDIT_LAB_SUCCESS'
export const EDIT_LAB_ERROR = 'EDIT_LAB_ERROR'
